# Generated by Django 3.1.2 on 2020-11-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=2020, max_length=50),
            preserve_default=False,
        ),
    ]
