# Generated by Django 3.0.5 on 2020-12-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='labels',
            new_name='label',
        ),
    ]
