# Generated by Django 3.0.5 on 2021-01-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0002_auto_20201224_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
    ]
