# Generated by Django 3.0.5 on 2021-01-05 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0004_user_user_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='user_log',
        ),
    ]
