# Generated by Django 3.0.5 on 2021-01-05 04:38

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0005_auto_20210105_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('fibre', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_log',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=200)),
                ('consumed_food', models.CharField(max_length=200)),
            ],
        ),
    ]
